name: path_morph
description: This package lets you create path tween animations. In other words, it lets you morph one path into another.
version: 2.0.0
homepage: https://github.com/hathibelagal-dev/path_morph_for_flutter

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
